- type: entity
  parent: BaseStructureStalkerDynamic
  id: STBaseHiddenCache
  abstract: true
  components:
    - type: Transform
      noRot: true
    - type: Storage
      maxItemSize: Large
      grid:
        - 0,0,8,8
    - type: ContainerContainer
      containers:
        storagebase: !type:Container
    - type: UserInterface
      interfaces:
        enum.StorageUiKey.Key:
          type: StorageBoundUserInterface
    - type: Clickable
    - type: Rangedetector