# Temporary
- type: Tag
  id: BlockMask
- type: Tag
  id: BlockBelt

###============------------------------------------============###
###============------------[New Одежда]------------============###
###============------------------------------------============###

###------------------------------###
###------------[База]------------###
###------------------------------###

- type: entity
  parent: ClothingOuterBase
  id: STClothingOuterBase
  suffix: ST
  abstract: true
  components:
  - type: RepositoryItem
    categoryName: Экипировка
  - type: PullDoAfter
    pullTime: 6

- type: entity
  parent: ClothingMaskGas
  id: STClothingMaskGas
  suffix: ST
  abstract: true
  components:
  - type: RepositoryItem
    categoryName: Экипировка
  - type: PullDoAfter
    pullTime: 2
  - type: HideLayerClothing
    slots:
    - Snout
    - FacialHair

- type: entity
  parent: ClothingOuterBaseLarge
  id: STClothingOuterBaseLarge
  suffix: ST
  abstract: true
  components:
  - type: RepositoryItem
    categoryName: Броня
  - type: PullDoAfter
    pullTime: 6

- type: entity
  parent: ClothingOuterArmorBasic
  id: STClothingOuterArmorBodyBase
  abstract: true
  suffix: ST

- type: entity
  parent: STClothingOuterArmorBodyBase
  id: STClothingOuterArmorStorageBasic
  name: база бронекостюмов с подсумками
  suffix: ST
  categories: [ HideSpawnMenu ]
  # abstract: true
  components:
  - type: Tag
    tags:
      - BlockBelt
      - Folder
  - type: RepositoryItem
    categoryName: Экипировка
  - type: Storage
    maxItemSize: Normal
    grid:
      - 0,2,0,3
      - 1,-0,1,-0
      - 2,2,2,3
      - 3,-0,3,-0
      - 4,2,4,3
    quickInsert: true
    areaInsert: true
  - type: ContainerContainer
    containers:
      storagebase: !type:Container
        ents: []
  - type: UserInterface
    interfaces:
      enum.StorageUiKey.Key:
        type: StorageBoundUserInterface
  - type: Dumpable

- type: entity
  parent: ClothingOuterArmorBasic
  id: ClothingOuterArmorStorageToggleableBasic
  name: база бронекостюмов с подсумками
  suffix: ST
  categories: [ HideSpawnMenu ]
  abstract: true
  components:
  - type: Storage
    maxItemSize: Normal
    grid:
      - 0,2,0,3
      - 1,-0,1,-0
      - 2,2,2,3
      - 3,-0,3,-0
      - 4,2,4,3
    quickInsert: true
    areaInsert: true
  - type: Tag
    tags:
      - BlockBelt
      - Folder
  - type: RepositoryItem
    categoryName: Экипировка
  - type: ToggleableClothing
    clothingPrototype: ClothingHeadHatHoodWinterDefault
    slot: head
  - type: ContainerContainer
    containers:
      toggleable-clothing: !type:ContainerSlot {}
      storagebase: !type:Container
        ents: []
  - type: UserInterface
    interfaces:
      enum.StorageUiKey.Key:
        type: StorageBoundUserInterface
  - type: Dumpable

- type: entity
  abstract: true
  id: STClothingHeadHatBase
  name: база встроенных голов
  suffix: ST
  description: Капюшоны, шлема и т.п. тема
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    state: icon
  - type: Clickable
  - type: Clothing
    equipSound: /Audio/Effects/rustle1.ogg
    unequipSound: /Audio/Effects/rustle2.ogg
    quickEquip: false
    slots: [ HEAD ]
  - type: GroupExamine
  - type: Tag
    tags:
    - HidesHair

- type: entity
  abstract: true
  parent: Clothing
  id: STClothingHeadBase
  name: База шлемов
  suffix: ST
  components:
  - type: Clothing
    slots:
    - HEAD
  - type: RepositoryItem
    categoryName: Экипировка
  - type: Sprite
    state: icon
  - type: Tag
    tags:
      - ClothMade
      - WhitelistChameleon
  - type: PullDoAfter
    pullTime: 2

- type: entity
  abstract: true
  parent: STClothingHeadBase
  id: ClothingHeadStalkerLightBase
  name: база шлемов с фонариком
  suffix: ST
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    layers:
    - state: icon
    - state: icon-flash
      visible: false
      map: [ "light" ]
  - type: Clothing
    equippedPrefix: off
  - type: Item
    heldPrefix: off
  - type: ToggleableLightVisuals
  - type: PointLight
    enabled: false
    radius: 3
    energy: 2
    mask: /Textures/Effects/LightMasks/cone.png
    autoRot: true
    netsync: false
  - type: Appearance
  - type: HandheldLight
    addPrefix: true
    blinkingBehaviourId: blinking
    radiatingBehaviourId: radiating
  - type: LightBehaviour
    behaviours:
      - !type:FadeBehaviour
        id: radiating
        interpolate: Linear
        maxDuration: 2.0
        startValue: 3.0
        endValue: 2.0
        isLooped: true
        reverseWhenFinished: true
      - !type:PulseBehaviour
        id: blinking
        interpolate: Nearest
        maxDuration: 1.0
        minValue: 0.1
        maxValue: 2.0
        isLooped: true
  - type: PowerCellSlot
    cellSlotId: cell_slot
  - type: ItemSlots
    slots:
      cell_slot:
        name: power-cell-slot-component-slot-name-default
        startingItem: PowerCellMedium
  - type: ContainerContainer
    containers:
      cell_slot: !type:ContainerSlot {}
  - type: Unremoveable

- type: entity
  abstract: true
  parent: ClothingBeltBase
  id: ClothingBeltStorageStalkerBase
  suffix: ST
  name: база РПС
  components:
  - type: Storage
    maxItemsize: Large
    grid:
    - 0,0,7,1
    quickInsert: true
    areaInsert: true
  - type: Item
    size: Ginormous
  - type: RepositoryItem
    categoryName: Снаряжение
  - type: ContainerContainer
    containers:
      storagebase: !type:Container
        ents: []
  - type: UserInterface
    interfaces:
      enum.StorageUiKey.Key:
        type: StorageBoundUserInterface
  - type: Dumpable
  - type: Tag
    tags:
      - Folder

- type: entity
  abstract: true
  parent: ClothingNeckBase
  id: STClothingCapeBase
  suffix: ST
  name: база плащей
  components:
  - type: Storage
    maxItemSize: Tiny
    grid:
      - 0,1,0,2
      - 2,1,2,2
  - type: UserInterface
    interfaces:
      enum.StorageUiKey.Key:
        type: StorageBoundUserInterface
  - type: ContainerContainer
    containers:
      toggleable-clothing: !type:ContainerSlot {}
  - type: Clothing
    equipDelay: 2
    slots:
    - CLOAK
  - type: RepositoryItem
    categoryName: Экипировка
  - type: Item
    size: Large
    shape:
      - 0,0,3,2

- type: entity
  parent: ClothingBackpackDuffel
  id: STClothingBackBase
  suffix: ST
  abstract: true
  components:
    - type: PullDoAfter
      pullTime: 3
    - type: ClothingSpeedModifier
      walkModifier: 1
      sprintModifier: 1
    - type: STWeight
      self: 1.5
    - type: Storage
      grid:
        - 0,0,4,4
      quickInsert: true
      areaInsert: true
    - type: RepositoryItem
      categoryName: Снаряжение
    - type: Dumpable
    - type: Tag
      tags:
      - Folder
    - type: Craftable

- type: entity
  id: STClothingBackTacticBase
  abstract: true
  parent: STClothingBackBase
  components:
  - type: Storage
    grid:
    - 0,0,6,5
