- type: job
  id: StalkerClearSky
  name: Боец Чистого Неба
  icon: cn
  description: Ищет способ сосуществования с Зоной.
  playTimeTracker: JobClearSky
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobClearSky
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: StalkerClearSkyGear
  supervisors: Исследуй Зону и оберегай её секреты от посторонних глаз.
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        tags:
          - CN
      - type: Bands
        band: Stalker
        bandIcon: cn
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3

- type: startingGear
  id: StalkerClearSkyGear
  equipment:
    id: ClearSkyPDA
    belt: ClothingBeltStorageWaistbag
    torso: ClothingTorsoSweaterStalkerGreen
    legs: ClothingLegsJeansBlue
    shoes: ClothingShoesBootsWork
    outerClothing: ClothingOuterCoatBomber
