
- type: job
  id: StalkerJournalist
  name: job-journalist
  icon: journalist
  description: job-journalist-desc
  playTimeTracker: JobJournalist
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobJournalist
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: JurGear
  supervisors: job-journalist-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Journalist
            - Stalker
        - type: Bands
          band: Stalker
          bandIcon: journalist
          bandProto: STJournalistsBand
          bandRankId: 2
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: JurGear
  equipment:
    id: StalkerPDA
    belt: ClothingBeltStorageWaistbag
    torso: ClothingTorsoSweaterStalkerGreen
    legs: ClothingLegsJeansBlue
    shoes: ClothingShoesBootsCombatFilled
- type: stBand
  id: STJournalistsBand
  name: Journalists
  factionId: Journalists
  maxMembers: 10
  managingRankId: 3
  hierarchy:
    1: StalkerJournalist

