- type: job
  id: StalkerMercenary
  name: Наёмник
  icon: merc
  description: Искатели приключений и головорезы со всего мира.
  playTimeTracker: JobStalkerMercenary
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobStalkerMercenary
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: StalkerMercenaryGear
  supervisors: Чётко спланированная операция с отличной подготовкой — вот залог вашего успеха.
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Merc
        - type: Bands
          band: Stalker
          bandIcon: merc
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: StalkerMercenaryGear
  equipment:
    id: BandPDA
    belt: ClothingBeltStorageWaistbag
    torso: STClothingTorsoJacketGray
    legs: STClothingLegsPantsGray
    shoes: ClothingShoesSwat


- type: job
  id: StalkerHeadMercenary
  name: Командир наёмников
  icon: merc
  description: Ваша обязанность - поддержка связи с штабом и непосредственное принятие решений по контракту.
  playTimeTracker: JobStalkerHeadMercenary
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobStalkerHeadMercenary
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: StalkerHeadMercenaryGear
  supervisors: вы координируете тактические операции, обеспечиваете эффективное взаимодействие членов группировки и принимаете оперативные решения на поле боя
  canBeAntag: false 
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - HeadMerc
            - Merc
        - type: Bands
          band: Stalker
          bandIcon: merc
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: StalkerHeadMercenaryGear
  equipment:
    id: BandPDA
    belt: ClothingBeltStorageWaistbag
    neck: ClothingNeckDogtagBrigand
    eyes: ClothingEyesGlassesSunglasses
    torso: STClothingTorsoJacketGray
    legs: STClothingLegsPantsGray
    shoes: ClothingShoesSwat
