
- type: job
  id: StalkerNeutral
  name: job-neutral-stalker
  icon: ne
  description: job-neutral-stalker-desc
  playTimeTracker: JobNeutral
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobNeutral
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: NeutralGear
  supervisors: job-neutral-stalker-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Neutral
            - Stalker
        - type: Bands
          band: Stalker
          bandIcon: ne
          bandProto: STNeutralBand
          bandRankId: 2
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: NeutralGear
  equipment:
    id: StalkerPDA
    belt: ClothingBeltStorageWaistbag
    torso: ClothingTorsoNeutral
    legs: ClothingLegsJeansNeutral
    shoes: ClothingShoesBootsCombatFilled
- type: stBand
  id: STNeutralBand
  name: Neutral
  factionId: Neutral
  maxMembers: 10
  managingRankId: 3
  hierarchy:
    1: StalkerNeutral

