- type: job
  id: StalkerPostulant
  name: job-postulant
  icon: pilgrim
  description: job-postulant-desc
  playTimeTracker: JobPostulant
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobPostulant
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: PilgrimPostulantGear
  supervisors: job-postulant-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: Psyonics
          psy: 50
        - type: PsyonicsActionLight
        - type: Access
          tags:
          - Pilgrim
          - Stalker
        - type: Bands
          band: Stalker
          bandIcon: pilgrim
          bandProto: STPilgrimsBand
          bandRankId: 2
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: job
  id: StalkerBishop
  name: job-bishop
  icon: pilgrim
  description: job-bishop-desc
  playTimeTracker: JobBishop
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobBishop
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: PilgrimMonkGear
  supervisors: job-bishop-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: Psyonics
          psy: 99
        - type: PsyonicsActionLight
          range: 10
          cost: 10
        - type: Access
          tags:
          - Pilgrim
          - Stalker
        - type: Bands
          band: Stalker
          bandIcon: pilgrim
          bandProto: STPilgrimsBand
          bandRankId: 2
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3


- type: startingGear
  id: PilgrimPostulantGear
  equipment:
    id: PilgrimPDA
    cloak: ClothingNeckDogtagPilgrim
    shoes: ClothingShoesBootsLaceup
    legs: ClothingLegsJeansBlackCargo
    torso: ClothingTorsoTShirtColorBlack
    pocket1: STPilgrimBible

- type: startingGear
  id: PilgrimMonkGear
  equipment:
    id: PilgrimPDA
    cloak: ClothingNeckCloakCassock
    shoes: ClothingShoesBootsLaceup
    legs: ClothingLegsJeansBlackCargo
    pocket1: STPilgrimBible
    torso: ClothingTorsoTShirtColorBlack
    pocket2: ClothingNeckDogtagPilgrim
- type: stBand
  id: STPilgrimsBand
  name: Pilgrims
  factionId: Pilgrims
  maxMembers: 10
  managingRankId: 3
  hierarchy:
    1: StalkerPostulant
    2: StalkerBishop

