- type: job
  id: StalkerPostulant
  name: Паломник
  icon: pilgrim
  description: Послушник в монашеском ордене
  playTimeTracker: JobPostulant
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobPostulant
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: PilgrimPostulantGear
  supervisors: Вы подчиняетесь все кто выше вас в иерархии
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: Psyonics
          psy: 50
        - type: PsyonicsActionLight
        - type: Access
          tags:
          - Pilgrim
          - Stalker
        - type: Bands
          band: Stalker
          bandIcon: pilgrim
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: job
  id: StalkerBishop
  name: Епископ
  icon: pilgrim
  description: глава монашеского ордена
  playTimeTracker: JobBishop
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobBishop
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: PilgrimMonkGear
  supervisors: Вы подчиняетесь только господу нашему Богу
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: Psyonics
          psy: 99
        - type: PsyonicsActionLight
          range: 10
          cost: 10
        - type: Access
          tags:
          - Pilgrim
          - Stalker
        - type: Bands
          band: Stalker
          bandIcon: pilgrim
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3


- type: startingGear
  id: PilgrimPostulantGear
  equipment:
    id: PilgrimPDA
    cloak: ClothingNeckDogtagPilgrim
    shoes: ClothingShoesBootsLaceup
    legs: ClothingLegsJeansBlackCargo
    torso: ClothingTorsoTShirtColorBlack
    pocket1: STPilgrimBible

- type: startingGear
  id: PilgrimMonkGear
  equipment:
    id: PilgrimPDA
    cloak: ClothingNeckCloakCassock
    shoes: ClothingShoesBootsLaceup
    legs: ClothingLegsJeansBlackCargo
    pocket1: STPilgrimBible
    torso: ClothingTorsoTShirtColorBlack
    pocket2: ClothingNeckDogtagPilgrim
