- type: job
  id: StalkerProjectPawn
  name: Следователь Проекта
  icon: project-1
  description: Они выполняют наставления алгоритма.
  playTimeTracker: JobProjectPawn
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobProjectPawn
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: ProjectPawnGear
  supervisors: Вы подчиняетесь Алгоритму и Оркестратору «Проекта»
  special:
    - !type:AddComponentSpecial
      components:
        - type: Psyonics
          psy: 300
        - type: PsyonicsActionSmoke 
          cost: 30
        - type: Access
          tags:
            - ProjectPawn
            - Project
            - Stalker
        - type: Bands
          band: Stalker
          altBand: project-2
          canChange: true
          bandIcon: project-1
        - type: IdentityBlocker
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: ProjectPawnGear
  equipment:
    id: ProjectPDA
    belt: ClothingBeltHolsterProject
    torso: ClothingTorsoJacketProjectPeshka
    legs: ClothingLegsJeansProjectPeshka
    shoes: ClothingShoesBootsProject
    ears: ClothingHeadsetProject
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesFingerless

- type: job
  id: StalkerProjectOrchestrator
  name: Оркестратор Проекта
  icon: project-3
  description: Следит за выполнением Алгоритма
  playTimeTracker: JobProjectOrchestrator
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobProjectOrchestrator
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: ProjectOrchestratorGear
  supervisors: Как Оркестратор, вы подчиняетесь непосредственно Алгоритму.
  special:
    - !type:AddComponentSpecial
      components:
        - type: Psyonics
          psy: 500
        - type: PsyonicsActionSmoke 
          cost: 30
        - type: PsyonicsActionRift
          cost: 50
        - type: Access
          tags:
            - ProjectPawn
            - ProjectOrchestrator
            - Project
            - Stalker
        - type: Bands
          band: Stalker
          altBand: project-4
          canChange: true
          bandIcon: project-3
        - type: BlockTackingHolyItems
        - type: IdentityBlocker
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: ProjectOrchestratorGear
  equipment:
    id: ProjectPDA
    belt: ClothingBeltHolsterProject
    torso: ClothingTorsoJacketProjectLeader
    legs: ClothingLegsJeansProjectLeader
    shoes: ClothingShoesBootsProject
    ears: ClothingHeadsetProject
    eyes: ClothingEyesHudProject
    gloves: ClothingHandsGlovesFingerless
