- type: job
  id: StalkerScientist
  name: Учёный
  icon: sci
  description: Основная цель - изучение всех аспектов Зоны, использование научных методов для дальнейшего объяснения того, что это за Зона и её предназначения.
  playTimeTracker: JobStalkerSci
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobStalkerSci
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: SciGear
  supervisors: Вы подчиняетесь старшему сотруднику и Институту.
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        groups:
          - Sci
      - type: Bands
        band: Stalker
        bandIcon: sci
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3

- type: job
  id: StalkerISSG
  name: Оперативник SSGI
  icon: ecologists
  description: Выполнения приказов института - ваше всё.
  playTimeTracker: JobStalkerISSG
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobStalkerSci
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: SciGear
  supervisors: Вы подчиняетесь старшему сотруднику и Институту.
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        groups:
          - Sci
      - type: Bands
        band: Stalker
        bandIcon: ecologists
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3

- type: job
  id: StalkerHeadScientist
  name: Ведущий Учёный
  icon: sci
  description: Основная цель - изучение всех аспектов Зоны, использование научных методов для дальнейшего объяснения того, что это за Зона и её предназначения.
  playTimeTracker: JobHeadStalkerSci
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobHeadStalkerSci
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: SciGear
  supervisors: Вы подчиняетесь старшему сотруднику и Институту.
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          groups:
            - SciHead
        - type: Bands
          band: Stalker
          bandIcon: sci
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: SciGear
  equipment:
    id: ScientistPDA
    legs: ClothingLegsJeansSandCargo
    shoes: ClothingShoesBootsCombatFilled
    torso: ClothingTorsoShirtWhiteScientific
