- type: job
  id: StalkerSBU
  name: Боец СБУ
  icon: sbu
  description: Член защиты службы безопасности Украины.
  playTimeTracker: JobSBU
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobSBU
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: MilitaryGear
  supervisors: Подчиняйся старшим по званию.
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          groups:
            - MilitaryHead
        - type: Bands
          altBand: stalker
          canChange: true
          band: Stalker
          bandIcon: sbu
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

