- type: job
  id: StalkerTulpari
  name: Чёрные тулпары
  icon: tulpari
  description: Казахи.
  playTimeTracker: JobTulpari
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobTulpari
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: TulGear
  supervisors: Вы никому не подчиняетесь...
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Stalker
        - type: Bands
          band: Stalker
          bandIcon: tulpari
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: TulGear
  equipment:
    id: StalkerPDA
    belt: ClothingBeltStorageWaistbag
    torso: ClothingTorsoTurtlenecksGorka6
    legs: ClothingLegsJeansGorka6
    shoes: ClothingShoesBootsCombat
    pocket1: PassportKazakhstan