name: Publish Arena

concurrency:
  group: publish

on:
  workflow_dispatch:

jobs:
  build:
    if: github.ref == 'refs/heads/ARENA14'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.6.0
      with:
        submodules: 'recursive'

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 8.0.100

    - name: Get Engine Tag
      run: |
        cd RobustToolbox
        git fetch --depth=1
    - name: Install dependencies
      run: dotnet restore

    - name: Build Packaging
      run: dotnet build Content.Packaging --configuration Release --no-restore /m

    - name: Package server
      run: dotnet run --project Content.Packaging server --platform win-x64 --platform linux-x64 --platform osx-x64 --platform linux-arm64

    - name: Package client
      run: dotnet run --project Content.Packaging client --no-wipe-release

    - name: Publish version
      run: Tools/publish_multi_request.py
      env:
        PUBLISH_TOKEN: ${{ secrets.ARENA_TOKEN }}
        FORK_ID: "arena"
